export const SIGNUP_TERMSSERVICE = Object.freeze({
  TITLE: "이용 약관에 동의해 주세요.",
  SUBTITLE:
    "필수 이용 약관에 동의하지 않으면\n서비스 사용에 제한이 있을 수 있습니다.",
  TERMS1: "서비스 이용 약관",
  TERMS1_CONTENT: "1111",
  TERMS2: "개인 정보 처리 방침",
  TERMS2_CONTENT: "2222",
  TERMS3: "수집하는 개인정보의 항목",
  TERMS3_CONTENT: "33333",
  TERMS4: "개인정보의 보유 및 이용기간",
  TERMS4_CONTENT: "4444",
  TERMS5: "개인정보의 보유 및 이용기간",
  TERMS5_CONTENT: "4444",
  TERMS6: "개인정보의 보유 및 이용기간",
  TERMS6_CONTENT: "4444",
  TERMS7: "개인정보의 보유 및 이용기간",
  TERMS7_CONTENT: "4444",
  TERMS8: "개인정보의 보유 및 이용기간",
  TERMS8_CONTENT: "4444",
  ALL_AGREE: "모든 이용 약관 동의",
  CONTINUE_SIGNUP: "회원 가입 계속하기",
});
